version: '3.7'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes: 
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: